### ISSUE TITLE
I am getting cross-origin error 

### ISSUE THREAD

**Issue by prakashchokalingam** [hirespace/dirty-markup-package#1]
I am getting cross-origin while am trying to clean up my html

`import cleaner from 'dirty-markup';`
 ` cleanHtml: function(html) {`
      `var options = {`
     `   code: html`
  `    };`
      `cleaner(options,function(data){`
       ` console.log(data);`
     `});`
 ` }`

<img width="1280" alt="screen shot 2016-11-02 at 2 19 39 pm" src="https://cloud.githubusercontent.com/assets/5512765/19922258/d4bbf020-a107-11e6-8b05-fd79fb887b74.png">

**Comment by Gilbert09** [comment]
@prakashchokalingam The package isn't meant for client side use purely for this reason.
